#!/usr/bin/env python


"""
Usage

"""


import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

coi = ["t_name", "FPKM"]
df893 = pd.read_csv( sys.argv[1], sep="\t" )[coi]
df915 = pd.read_csv( sys.argv[2], sep="\t" )[coi]
df_merge = pd.merge( df893, df915, on = "t_name")

x = df_merge["FPKM_x"]
y = df_merge["FPKM_y"]


fig = plt.figure()
plt.scatter((x),(y), alpha = 0.3)
fig.suptitle('FPKM of df893 vs df915', fontsize=20)
plt.xlabel("FPKM df893")
plt.xlim(0,100000)
plt.xscale('symlog')
plt.ylabel("FPKM df915")
plt.ylim(0,100000)
plt.yscale('symlog')
plt.plot(np.unique(x), np.poly1d(np.polyfit(x, y, deg = 1))(np.unique(x)), color = "r")
plt.savefig( sys.argv[3] + ".png" )
plt.close()